### ISSUE TITLE
 loading bam or bigwig files gives error

### ISSUE THREAD

**Issue by xiao00su** [RockefellerUniversity/profileplyr#12]
I run the following code to load bam or bigwig files:

```
BamBigwig_to_chipProfile(signalFiles = dirBW[5:8], format = 'bigwig', testRanges = TSS, 
                         style = "point", bin_size = 20, distanceAround = NULL, distanceUp = 1000,distanceDown = 1000,  quant_params = NULL)

```
Loading bigwig files.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘import’ for signature ‘"GRanges", "missing", "missing"’

Could anyone provide some help?

**Comment by dougbarrows** [comment]
Hi there - it looks like the input for 'testRanges' is a GRanges object (called 'TSS' in your function call). Is that true? Currently this function requires a path to a bed file, and a GRanges won't work. You can just write that GRanges object you have to a bed file with the rtracklayer package, and then use the path that file for 'testRanges'

**Comment by dougbarrows** [comment]
I will close this since the issue has hopefully been resolved, but if you are still having a problem, let me know and I will open the issue back up.
