### ISSUE TITLE
Error in generateEnrichedHeatmap for ylim as numeric vector

### ISSUE THREAD

**Issue by JSegueni** [RockefellerUniversity/profileplyr#9]
Hi all,

I'm using the DiffBind package for my analysis and it uses your great generateEnrichedHeatmap() function to plot profiles.

I'm trying to set the ylim of the generated heatmaps but I'm getting the following error:

Error in if (ylim %in% colnames(sampleData(object))) {: the condition has length > 1

It comes from this line:
"if (ylim %in% colnames(sampleData(object))) {"

The issue comes from the order of the checked conditions, the function should not check first if the ylim is a column in the sampleData but first if it is a numeric vector or a list, since "the if() function can only check one element to evaluate a condition" and otherwise gives an error.

If I'm correct in my assessment, would it be possible to fix the bug and push the new version of the package?

Thank you for your work!

Best wishes.

**Comment by ggmirizio** [comment]
Hi, 

I am having the exact same issue as @JSegueni. In my case, I'm using the Profileplyr package and when trying to set up the ylim for all my plots as a list, I'm getting the following error: 

Error in if (ylim %in% colnames(sampleData(object))) {: the condition has length > 1

I have 4 heatmaps concatenated so my script looks like this (although the ylim argument it's not working):
generateEnrichedHeatmap(proplyr_object_subset,
                        include_group_annotation = TRUE, 
                        matrices_color = c("white", "black"),
                        ylim = list(c(-0.02,0.07),c(0.03,0.07),c(0.02,0.06),c(-0.03,0.02)),
                        all_color_scales_equal = FALSE)

Could you please check and fix the bug? I use this package for everything and love it. 

Best, 

Gerardo

**Comment by dougbarrows** [comment]
Hi all, apologies for taking a while, we missed the original post. Thank you for pointing out this bug! It has been fixed in the most recent version of the package (1.14.1) and you should be able to set multiple y-limits to the heatmaps without an error.
